[mypy]

# Only check files that have at least one type hint or a 'pass'
check_untyped_defs = False
# Don't error out if a function doesn't have hints yet
disallow_untyped_defs = False
# Stop the "noise" from libraries
ignore_missing_imports = True

# To start off, I'll have all errors ignored by default.  The per-module options below
# then let specific files be checked 
#ignore_errors = True

# Error when a function returns a value inferred to have type Any
#warn_return_any = True

# Report any config options that are unused by mypy. (This will help us catch typos when
# making changes to our config file).
warn_unused_configs = True

warn_return_any = True

# Things to ignore
[mypy-mpmath.*]
ignore_missing_imports = True
[mypy-uncertainties.*]
ignore_missing_imports = True

# ---------------------------------------------------------------------------
# Per-module options

[dp*.py]
ignore_errors = False

